on:
  push:
    branches:
      - main
    paths:
      - js/packages/web/**
jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: js
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: js/package-lock.json
      - run: npm ci
      - run: npm run build
        working-directory: js/packages/web
      - uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: js/packages/web
