on:
  release:
    types:
      - published
jobs:
  deploy:
    if: startsWith(github.event.release.tag_name, 'core_')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: core
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --build-secret SENTEY_KEY=${{ secrets.SENTEY_KEY }} OPENREPLAY_KEY=${{ secrets.OPENREPLAY_KEY }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
